//导出所有的action

export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
  POPULAR_REF:'POPULAR_REF',
  LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
  LOAD_POPULAR_SUC:'LOAD_POPULAR_SUC',
  LOADMORE_POPULAR_SUC:'LOADMORE_POPULAR_SUC',
  LOADMORE_POPULAR_FAIL:'LOADMORE_POPULAR_FAIL',
  //刷新favorite收藏状态
  FLUSH_POPULAR_FAVORITE:'FLUSH_POPULAR_FAVORITE',
  //trending 页面
  TRENDING_REF:'TRENDING_REF',
  LOAD_TRENDING_FAIL:'LOAD_TRENDING_REF_FAIL',
  LOAD_TRENDING_SUC:'LOAD_TRENDING_REF_SUC',
  LOADMORE_TRENDING_SUC:'LOADMORE_TRENDING_SUC',
  LOADMORE_TRENDING_FAIL:'LOADMORE_TRENDING_FAIL',
  FLUSH_TRENDING_FAVORITE:'FLUSH_TRENDING_FAVORITE',

  // 收藏页面
  FAVORITE_LOAD_DATA:'FAVORITE_LOAD_DATA',
  FAVORITE_LOAD_FAIL:'FAVORITE_LOAD_FAIL',
  FAVORITE_LOAD_SUC:'FAVORITE_LOAD_SUC',

  // 加载语言数据
  LAUGUAGE_LOAD_SUC:'LAUGUAGE_LOAD_SUC',
};


