//导出所有的action

export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REF:'POPULAR_REF',
  LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
  LOAD_POPULAR_SUC:'LOAD_POPULAR_SUC',
  LOADMORE_POPULAR_SUC:'LOADMORE_POPULAR_SUC',
  LOADMORE_POPULAR_FAIL:'LOADMORE_POPULAR_FAIL',

};
